contracts/.gitignore, contracts/README.md, contracts/contracts/Gateway.sol, contracts/contracts/interfaces/IGateway.sol, contracts/hardhat.config.js, contracts/package.json, contracts/scripts/sample-script.js, contracts/test/Gateway.js
* Add Gateway Contract to receives and responses messages from off-chain nodes.
=> Implement Gateway Contract

contracts/contracts/Gateway.sol, contracts/contracts/Marketplace.sol, contracts/contracts/interfaces/IGateway.sol, contracts/contracts/mocks/MockERC1155.sol, contracts/contracts/mocks/MockERC20.sol, contracts/contracts/mocks/MockERC721.sol, contracts/test/Gateway.js, contracts/test/Helpers/index.js, contracts/test/Marketplace.js
* Add Marketplace Contract
* Add Tests for intra-chain swaps
=> Add Marketplace Contract

contracts/contracts/Marketplace.sol, contracts/test/Marketplace.js
* Add test cases for cross-chain swaps
=> Test cases for Cross-Chain Swaps

frontend/src/components/CreateOrder/confirm.js, frontend/src/components/CreateOrder/from.js, frontend/src/components/CreateOrder/index.js, frontend/src/components/CreateOrder/to.js, frontend/src/components/OrderDetails/index.js, frontend/src/components/alert.js, frontend/src/components/footer.js
* Minor UI improvements on new order page
=> Minor UI improvements

frontend/src/components/OrderDetails/assetCard.js, frontend/src/components/OrderDetails/index.js, frontend/src/components/jumbotron.js, frontend/src/components/lists.js, frontend/src/components/nftCard.js, frontend/src/constants/index.js, frontend/src/hooks/useOrder.js
- Reveals the NFT metadata such as Name, Description through Moralis API
=> Reveals NFT metadata

frontend/src/abi/erc20.json, frontend/src/components/CreateOrder/confirm.js, frontend/src/components/CreateOrder/from.js, frontend/src/components/CreateOrder/index.js, frontend/src/components/CreateOrder/to.js, frontend/src/components/OrderDetails/assetCard.js, frontend/src/components/OrderDetails/index.js, frontend/src/components/lists.js, frontend/src/config/connectors.js, frontend/src/config/network.js, frontend/src/hooks/useOrder.js
* Support ERC-20 tokens when create an order entry
* Complete intra-chain swaps function
=> Support ERC-20 tokens

frontend/src/components/Home/index.js, frontend/src/components/Home/mintToken.js, frontend/src/components/OrderDetails/assetCard.js, frontend/src/components/buttons.js, frontend/src/components/header.js, frontend/src/components/lists.js, frontend/src/constants/index.js
* Make minor UI improvements before go-live
=> Final UI improvements

frontend/src/components/Home/mintToken.js, frontend/src/components/Modal/CrosschainSwapModal.js, frontend/src/components/OrderDetails/assetCard.js, frontend/src/components/OrderDetails/index.js, frontend/src/hooks/useInterval.js
* Add countdown at the approval step when a user swaps tokens across the chain.
=> Countdown at the approval step

frontend/src/components/CreateOrder/index.js, frontend/src/hooks/useOrder.js
* Not sure why sometime Moralis API returns URL without the prefix, so we're overriding here.
=> Missing HTTPS prefixes

frontend/src/App.js, frontend/src/components/Account/connect.js, frontend/src/components/Account/orders.js, frontend/src/components/CreateOrder/to.js, frontend/src/components/Faucet/index.js, frontend/src/components/Modal/CrosschainSwapModal.js, frontend/src/components/Modal/SwapModal.js, frontend/src/components/OrderDetails/assetCard.js, frontend/src/components/OrderDetails/index.js, frontend/src/components/alert.js, frontend/src/components/cards.js, frontend/src/components/header.js, frontend/src/components/lists.js, frontend/src/components/nftCard.js, frontend/src/constants/index.js, frontend/src/hooks/useERC1155.js, frontend/src/hooks/useERC20.js, frontend/src/hooks/useERC721.js, frontend/src/hooks/useOrder.js, frontend/src/mocks/index.js
- Add pre-swap modal for intra-chain swaps
- Separate token approval logics
- Refactor corss-chain swaps modal + proof checking
=> Pre-swap Modal

frontend/package.json, frontend/src/components/Account/index.js, frontend/src/components/Account/orders.js, frontend/src/components/Collection/index.js, frontend/src/components/CreatorPage/index.js, frontend/src/components/Home/index.js, frontend/src/components/header.js, frontend/src/components/jumbotron.js, frontend/src/components/rankBoard.js, frontend/src/hooks/useOrder.js
* Add Ranking Board
* New Header Design
=> Ranking Board

backend/functions/utils/index.js, frontend/src/components/CreateOrder/index.js, frontend/src/components/CreateOrder/to.js, frontend/src/components/Faucet/index.js, frontend/src/components/OrderDetails/index.js, frontend/src/components/nftCard.js, frontend/src/constants/index.js, frontend/src/hooks/useOrder.js, frontend/src/mocks/index.js
* Support BNB and AVAX testnet when create an order
* Fixing mock NFT on BNB testnet
=> Support BNB / AVAX testnet

frontend/src/components/Account/index.js, frontend/src/components/Account/orders.js, frontend/src/components/Collection/index.js, frontend/src/components/OrderDetails/index.js, frontend/src/components/footer.js, frontend/src/components/header.js, frontend/src/components/jumbotron.js, frontend/src/helper/index.js, frontend/src/hooks/useActivities.js
* Add activities / metadata sections on the entry page
=> Order Activities

frontend/src/components/Account/history.js, frontend/src/components/Account/index.js, frontend/src/hooks/useActivities.js
* Allows users to see their trade history on the account page
=> Trade History

frontend/src/components/Account/history.js, frontend/src/components/Modal/CrosschainSwapModal.js, frontend/src/components/OrderDetails/index.js, frontend/src/constants/index.js, frontend/src/helper/index.js, frontend/src/hooks/useActivities.js, frontend/src/hooks/useMoralisAPI.js, frontend/src/hooks/useOrder.js, frontend/src/hooks/useProof.js, services/package.json, services/validator/index.js, services/validator/tickets.js
* Allows validators to issue claims for sellers
* Updates the frontend to recognize the new state root generated by the validator
=> Validators to issue claims for sellers

frontend/src/components/Account/history.js, frontend/src/components/Account/orders.js, frontend/src/components/OrderDetails/activities.js, frontend/src/components/OrderDetails/index.js, frontend/src/components/OrderDetails/metadata.js, frontend/src/components/OrderDetails/pending.js, frontend/src/constants/index.js, frontend/src/hooks/useActivities.js, frontend/src/hooks/useOrder.js, frontend/src/hooks/useProof.js, services/validator/tickets.js
* Resolve mock's metadata from the client side to reduce requests to Moralis API
* Add timeout when resolve metadata from cache endpoints
=> Resolve mock's metadata from the client side

frontend/src/components/Account/history.js, frontend/src/components/Account/orders.js, frontend/src/components/OrderDetails/activities.js, frontend/src/components/OrderDetails/index.js, frontend/src/components/OrderDetails/metadata.js, frontend/src/components/OrderDetails/pending.js, frontend/src/constants/index.js, frontend/src/hooks/useActivities.js, frontend/src/hooks/useOrder.js, frontend/src/hooks/useProof.js, services/validator/tickets.js
* Add claim panel for the seller, the panel will be appeared on the order page if the seller has pending claim.
=> Claim Panel for Seller

frontend/src/components/Account/connect.js, frontend/src/components/AllCollectionPage/index.js, frontend/src/components/Collection/index.js, frontend/src/components/CreateOrder/confirm.js, frontend/src/components/CreateOrder/from.js, frontend/src/components/CreateOrder/index.js, frontend/src/components/CreateOrder/to.js, frontend/src/components/Faucet/index.js, frontend/src/components/Home/howItWorks.js, frontend/src/components/Home/index.js, frontend/src/components/Modal/SwitchChainModal.js, frontend/src/components/cards.js, frontend/src/components/header.js, frontend/src/components/rankBoard.js, frontend/src/config/connectors.js, frontend/src/config/network.js, frontend/src/constants/index.js, frontend/src/helper/index.js, frontend/src/hooks/useMoralisAPI.js, frontend/src/hooks/useOpenSea.js, frontend/src/hooks/useOrder.js, services/constants/index.js, services/helper/index.js, services/validator/tickets.js
* Update services and the frontend to support Mainnet's smart contract
=> Mainnet support

frontend/src/components/Home/howItWorks.js, frontend/src/components/Home/index.js, frontend/src/components/rankBoard.js
=> How To Panel

frontend/src/components/Account/connect.js, frontend/src/components/CreateOrder/confirm.js, frontend/src/components/Home/faq.js, frontend/src/components/Home/index.js, frontend/src/components/cards.js, frontend/src/config/connectors.js, frontend/src/config/network.js, frontend/src/constants/index.js, frontend/src/helper/index.js, frontend/src/hooks/useMoralisAPI.js, frontend/src/hooks/useOpenSea.js, services/constants/index.js, services/helper/index.js, services/relayer/index.js, services/validator/index.js, services/validator/tickets.js
* Update constants on both frontend and service modules to support ETH mainnet.
=> Support ETH mainnet

services/helper/index.js, services/relayer/index.js, services/validator/index.js
* Estimate gas prices from 3rd party API
=> Estimate Gas Prices 

frontend/src/components/Account/orders.js, frontend/src/hooks/useOrder.js, frontend/src/hooks/useProof.js, services/relayer/index.js, services/validator/index.js, services/validator/tickets.js
* Shorten time to generate validator's messages
* Update the frontend to use the new approach
=> Validator Optimization
